// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tensorflow/core/protobuf/worker.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2016 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Tensorflow_GetStatusRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".GetStatusRequest"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_GetStatusResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".GetStatusResponse"

  public var deviceAttributes: [Tensorflow_DeviceAttributes] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.deviceAttributes)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.deviceAttributes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.deviceAttributes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_CreateWorkerSessionRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CreateWorkerSessionRequest"

  /// Sessions are identified by a given handle.
  public var sessionHandle: String {
    get {return _storage._sessionHandle}
    set {_uniqueStorage()._sessionHandle = newValue}
  }

  /// Defines the configuration of a TensorFlow worker.
  public var serverDef: Tensorflow_ServerDef {
    get {return _storage._serverDef ?? Tensorflow_ServerDef()}
    set {_uniqueStorage()._serverDef = newValue}
  }
  /// Returns true if `serverDef` has been explicitly set.
  public var hasServerDef: Bool {return _storage._serverDef != nil}
  /// Clears the value of `serverDef`. Subsequent reads from it will return its default value.
  public mutating func clearServerDef() {_storage._serverDef = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._sessionHandle)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._serverDef)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._sessionHandle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sessionHandle, fieldNumber: 1)
      }
      if let v = _storage._serverDef {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_CreateWorkerSessionResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CreateWorkerSessionResponse"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_RegisterGraphRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RegisterGraphRequest"

  /// Subgraphs are scoped within one session.
  public var sessionHandle: String {
    get {return _storage._sessionHandle}
    set {_uniqueStorage()._sessionHandle = newValue}
  }

  /// "graph_def" has the subgraph of nodes for this worker, with each node
  /// having its device_name filled in.
  public var graphDef: Tensorflow_GraphDef {
    get {return _storage._graphDef ?? Tensorflow_GraphDef()}
    set {_uniqueStorage()._graphDef = newValue}
  }
  /// Returns true if `graphDef` has been explicitly set.
  public var hasGraphDef: Bool {return _storage._graphDef != nil}
  /// Clears the value of `graphDef`. Subsequent reads from it will return its default value.
  public mutating func clearGraphDef() {_storage._graphDef = nil}

  /// True iff the graph (before partitioning) contains control flow nodes.
  ///
  /// As of 01/11/2015, this is no longer set by clients.
  public var hasControlFlow_p: Bool {
    get {return _storage._hasControlFlow_p}
    set {_uniqueStorage()._hasControlFlow_p = newValue}
  }

  /// Configuration options for the session in which this graph was created.
  public var graphOptions: Tensorflow_GraphOptions {
    get {return _storage._graphOptions ?? Tensorflow_GraphOptions()}
    set {_uniqueStorage()._graphOptions = newValue}
  }
  /// Returns true if `graphOptions` has been explicitly set.
  public var hasGraphOptions: Bool {return _storage._graphOptions != nil}
  /// Clears the value of `graphOptions`. Subsequent reads from it will return its default value.
  public mutating func clearGraphOptions() {_storage._graphOptions = nil}

  /// Field(s) used by TensorFlow Debugger (tfdbg).
  public var debugOptions: Tensorflow_DebugOptions {
    get {return _storage._debugOptions ?? Tensorflow_DebugOptions()}
    set {_uniqueStorage()._debugOptions = newValue}
  }
  /// Returns true if `debugOptions` has been explicitly set.
  public var hasDebugOptions: Bool {return _storage._debugOptions != nil}
  /// Clears the value of `debugOptions`. Subsequent reads from it will return its default value.
  public mutating func clearDebugOptions() {_storage._debugOptions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._sessionHandle)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._graphDef)
        case 3: try decoder.decodeSingularBoolField(value: &_storage._hasControlFlow_p)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._graphOptions)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._debugOptions)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._sessionHandle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sessionHandle, fieldNumber: 1)
      }
      if let v = _storage._graphDef {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if _storage._hasControlFlow_p != false {
        try visitor.visitSingularBoolField(value: _storage._hasControlFlow_p, fieldNumber: 3)
      }
      if let v = _storage._graphOptions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._debugOptions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_RegisterGraphResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RegisterGraphResponse"

  /// If the registration succeeds, returns an opaque graph_handle to
  /// the master. The master calls RunGraph with graph_handle to
  /// compute different steps.
  public var graphHandle: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.graphHandle)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.graphHandle.isEmpty {
      try visitor.visitSingularStringField(value: self.graphHandle, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_DeregisterGraphRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".DeregisterGraphRequest"

  /// The session_handle used when registering the graph. If session_handle is
  /// empty, a single global namespace is used.
  public var sessionHandle: String = String()

  /// REQUIRED: graph_handle must be returned by a RegisterGraph call
  /// to the same WorkerService.
  public var graphHandle: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.graphHandle)
      case 2: try decoder.decodeSingularStringField(value: &self.sessionHandle)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.graphHandle.isEmpty {
      try visitor.visitSingularStringField(value: self.graphHandle, fieldNumber: 1)
    }
    if !self.sessionHandle.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionHandle, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

/// TODO(mrry): Optionally add summary stats for the graph.
public struct Tensorflow_DeregisterGraphResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".DeregisterGraphResponse"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_CleanupAllRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CleanupAllRequest"

  /// A list of container names.
  ///
  /// If 'container' is not empty, releases resources in the given
  /// containers in all devices.
  ///
  /// If 'container' is empty, releases resources in the default
  /// container in all devices.
  public var container: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedStringField(value: &self.container)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.container.isEmpty {
      try visitor.visitRepeatedStringField(value: self.container, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_CleanupAllResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CleanupAllResponse"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

/// Options specific to the execution of a single step.
public struct Tensorflow_ExecutorOpts: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".ExecutorOpts"

  public var recordCosts: Bool = false

  public var recordTimeline: Bool = false

  public var recordPartitionGraphs: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.recordCosts)
      case 3: try decoder.decodeSingularBoolField(value: &self.recordTimeline)
      case 4: try decoder.decodeSingularBoolField(value: &self.recordPartitionGraphs)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.recordCosts != false {
      try visitor.visitSingularBoolField(value: self.recordCosts, fieldNumber: 1)
    }
    if self.recordTimeline != false {
      try visitor.visitSingularBoolField(value: self.recordTimeline, fieldNumber: 3)
    }
    if self.recordPartitionGraphs != false {
      try visitor.visitSingularBoolField(value: self.recordPartitionGraphs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_RunGraphRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RunGraphRequest"

  /// session_handle is the master-generated unique id for this session.
  /// If session_handle is non-empty, it must be the same as used when
  /// registering the graph. If it is empty, a single global namespace is used to
  /// search for the graph_handle.
  public var sessionHandle: String {
    get {return _storage._sessionHandle}
    set {_uniqueStorage()._sessionHandle = newValue}
  }

  /// REQUIRED: graph_handle must be returned by a RegisterGraph call
  /// to the same WorkerService.
  public var graphHandle: String {
    get {return _storage._graphHandle}
    set {_uniqueStorage()._graphHandle = newValue}
  }

  /// A unique ID to distinguish different runs of the same graph.
  ///
  /// The master generates a global unique `step_id` to distinguish
  /// different runs of the graph computation. Subgraphs communicate
  /// (e.g., send/recv ops) with each other using `step_id` to
  /// distinguish tensors generated by different runs.
  public var stepID: Int64 {
    get {return _storage._stepID}
    set {_uniqueStorage()._stepID = newValue}
  }

  /// Options for this step.
  public var execOpts: Tensorflow_ExecutorOpts {
    get {return _storage._execOpts ?? Tensorflow_ExecutorOpts()}
    set {_uniqueStorage()._execOpts = newValue}
  }
  /// Returns true if `execOpts` has been explicitly set.
  public var hasExecOpts: Bool {return _storage._execOpts != nil}
  /// Clears the value of `execOpts`. Subsequent reads from it will return its default value.
  public mutating func clearExecOpts() {_storage._execOpts = nil}

  /// Runs the graph.
  ///
  /// Sends the tensors in "send" into the graph before the run and
  /// fetches the keys into `RunGraphResponse.recv` after the run.
  public var send: [Tensorflow_NamedTensorProto] {
    get {return _storage._send}
    set {_uniqueStorage()._send = newValue}
  }

  public var recvKey: [String] {
    get {return _storage._recvKey}
    set {_uniqueStorage()._recvKey = newValue}
  }

  /// True if the RunGraphRequest is a partial run request.
  public var isPartial: Bool {
    get {return _storage._isPartial}
    set {_uniqueStorage()._isPartial = newValue}
  }

  /// True if this is the last partial run request in a sequence of requests.
  public var isLastPartialRun: Bool {
    get {return _storage._isLastPartialRun}
    set {_uniqueStorage()._isLastPartialRun = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._graphHandle)
        case 2: try decoder.decodeSingularInt64Field(value: &_storage._stepID)
        case 3: try decoder.decodeRepeatedMessageField(value: &_storage._send)
        case 4: try decoder.decodeRepeatedStringField(value: &_storage._recvKey)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._execOpts)
        case 6: try decoder.decodeSingularBoolField(value: &_storage._isPartial)
        case 7: try decoder.decodeSingularBoolField(value: &_storage._isLastPartialRun)
        case 8: try decoder.decodeSingularStringField(value: &_storage._sessionHandle)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._graphHandle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._graphHandle, fieldNumber: 1)
      }
      if _storage._stepID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._stepID, fieldNumber: 2)
      }
      if !_storage._send.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._send, fieldNumber: 3)
      }
      if !_storage._recvKey.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._recvKey, fieldNumber: 4)
      }
      if let v = _storage._execOpts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if _storage._isPartial != false {
        try visitor.visitSingularBoolField(value: _storage._isPartial, fieldNumber: 6)
      }
      if _storage._isLastPartialRun != false {
        try visitor.visitSingularBoolField(value: _storage._isLastPartialRun, fieldNumber: 7)
      }
      if !_storage._sessionHandle.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sessionHandle, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_RunGraphResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RunGraphResponse"

  /// A list of tensors corresponding to those requested by
  /// `RunGraphRequest.recv_key`.
  public var recv: [Tensorflow_NamedTensorProto] {
    get {return _storage._recv}
    set {_uniqueStorage()._recv = newValue}
  }

  /// If the request asked for execution stats, the cost graph, or the partition
  /// graphs, these are returned here.
  /// TODO(suharshs): Package these in a RunMetadata instead.
  public var stepStats: Tensorflow_StepStats {
    get {return _storage._stepStats ?? Tensorflow_StepStats()}
    set {_uniqueStorage()._stepStats = newValue}
  }
  /// Returns true if `stepStats` has been explicitly set.
  public var hasStepStats: Bool {return _storage._stepStats != nil}
  /// Clears the value of `stepStats`. Subsequent reads from it will return its default value.
  public mutating func clearStepStats() {_storage._stepStats = nil}

  public var costGraph: Tensorflow_CostGraphDef {
    get {return _storage._costGraph ?? Tensorflow_CostGraphDef()}
    set {_uniqueStorage()._costGraph = newValue}
  }
  /// Returns true if `costGraph` has been explicitly set.
  public var hasCostGraph: Bool {return _storage._costGraph != nil}
  /// Clears the value of `costGraph`. Subsequent reads from it will return its default value.
  public mutating func clearCostGraph() {_storage._costGraph = nil}

  public var partitionGraph: [Tensorflow_GraphDef] {
    get {return _storage._partitionGraph}
    set {_uniqueStorage()._partitionGraph = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeRepeatedMessageField(value: &_storage._recv)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._stepStats)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._costGraph)
        case 4: try decoder.decodeRepeatedMessageField(value: &_storage._partitionGraph)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._recv.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._recv, fieldNumber: 1)
      }
      if let v = _storage._stepStats {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._costGraph {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if !_storage._partitionGraph.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._partitionGraph, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_CleanupGraphRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CleanupGraphRequest"

  public var stepID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt64Field(value: &self.stepID)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stepID != 0 {
      try visitor.visitSingularInt64Field(value: self.stepID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_CleanupGraphResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".CleanupGraphResponse"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_RecvTensorRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RecvTensorRequest"

  /// The step in which the tensor will be produced.
  ///
  /// REQUIRED: This must eventually correspond to the `step_id` passed
  /// into a RunGraph call on the same WorkerService.
  public var stepID: Int64 {
    get {return _storage._stepID}
    set {_uniqueStorage()._stepID = newValue}
  }

  /// A key that identifies the tensor to be received.
  public var rendezvousKey: String {
    get {return _storage._rendezvousKey}
    set {_uniqueStorage()._rendezvousKey = newValue}
  }

  /// If true, use an out-of-band DMA mechanism to transfer the
  /// received tensor.
  public var dmaOk: Bool {
    get {return _storage._dmaOk}
    set {_uniqueStorage()._dmaOk = newValue}
  }

  /// Optional information on client-side device locality.
  public var clientLocality: Tensorflow_DeviceLocality {
    get {return _storage._clientLocality ?? Tensorflow_DeviceLocality()}
    set {_uniqueStorage()._clientLocality = newValue}
  }
  /// Returns true if `clientLocality` has been explicitly set.
  public var hasClientLocality: Bool {return _storage._clientLocality != nil}
  /// Clears the value of `clientLocality`. Subsequent reads from it will return its default value.
  public mutating func clearClientLocality() {_storage._clientLocality = nil}

  /// Optional information on server-side device locality.
  public var serverLocality: Tensorflow_DeviceLocality {
    get {return _storage._serverLocality ?? Tensorflow_DeviceLocality()}
    set {_uniqueStorage()._serverLocality = newValue}
  }
  /// Returns true if `serverLocality` has been explicitly set.
  public var hasServerLocality: Bool {return _storage._serverLocality != nil}
  /// Clears the value of `serverLocality`. Subsequent reads from it will return its default value.
  public mutating func clearServerLocality() {_storage._serverLocality = nil}

  /// Optional information needed by the RPC subsystem.
  public var transportOptions: SwiftProtobuf.Google_Protobuf_Any {
    get {return _storage._transportOptions ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_uniqueStorage()._transportOptions = newValue}
  }
  /// Returns true if `transportOptions` has been explicitly set.
  public var hasTransportOptions: Bool {return _storage._transportOptions != nil}
  /// Clears the value of `transportOptions`. Subsequent reads from it will return its default value.
  public mutating func clearTransportOptions() {_storage._transportOptions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt64Field(value: &_storage._stepID)
        case 2: try decoder.decodeSingularStringField(value: &_storage._rendezvousKey)
        case 3: try decoder.decodeSingularBoolField(value: &_storage._dmaOk)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._clientLocality)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._serverLocality)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._transportOptions)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._stepID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._stepID, fieldNumber: 1)
      }
      if !_storage._rendezvousKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._rendezvousKey, fieldNumber: 2)
      }
      if _storage._dmaOk != false {
        try visitor.visitSingularBoolField(value: _storage._dmaOk, fieldNumber: 3)
      }
      if let v = _storage._clientLocality {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._serverLocality {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._transportOptions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_RecvTensorResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".RecvTensorResponse"

  /// The tensor as a proto.
  public var tensor: Tensorflow_TensorProto {
    get {return _storage._tensor ?? Tensorflow_TensorProto()}
    set {_uniqueStorage()._tensor = newValue}
  }
  /// Returns true if `tensor` has been explicitly set.
  public var hasTensor: Bool {return _storage._tensor != nil}
  /// Clears the value of `tensor`. Subsequent reads from it will return its default value.
  public mutating func clearTensor() {_storage._tensor = nil}

  /// If true, this tensor was the output of a dead node, and the
  /// content is invalid.
  public var isDead: Bool {
    get {return _storage._isDead}
    set {_uniqueStorage()._isDead = newValue}
  }

  /// The time at which tensor was available and started to be returned.
  public var sendStartMicros: Int64 {
    get {return _storage._sendStartMicros}
    set {_uniqueStorage()._sendStartMicros = newValue}
  }

  /// Optional additional information about how to receive the tensor,
  /// e.g. in the event that `RecvTensorRequest.dma_ok` was true.
  public var transportOptions: SwiftProtobuf.Google_Protobuf_Any {
    get {return _storage._transportOptions ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_uniqueStorage()._transportOptions = newValue}
  }
  /// Returns true if `transportOptions` has been explicitly set.
  public var hasTransportOptions: Bool {return _storage._transportOptions != nil}
  /// Clears the value of `transportOptions`. Subsequent reads from it will return its default value.
  public mutating func clearTransportOptions() {_storage._transportOptions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._tensor)
        case 2: try decoder.decodeSingularBoolField(value: &_storage._isDead)
        case 3: try decoder.decodeSingularInt64Field(value: &_storage._sendStartMicros)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._transportOptions)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._tensor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._isDead != false {
        try visitor.visitSingularBoolField(value: _storage._isDead, fieldNumber: 2)
      }
      if _storage._sendStartMicros != 0 {
        try visitor.visitSingularInt64Field(value: _storage._sendStartMicros, fieldNumber: 3)
      }
      if let v = _storage._transportOptions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Out-of-band request to begin or end logging, or
/// to retrieve logs for particular steps.
public struct Tensorflow_LoggingRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".LoggingRequest"

  /// If true, RPC logging will be activated.
  public var rpcLogging: Bool = false

  /// If true, discard any saved logging data (for all steps).
  public var clear: Bool = false

  /// When set, requests all saved log data pertaining to the step.
  /// Any log data retrieved is eliminated from the store and cannot be
  /// retrieved again.
  public var fetchStepID: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.rpcLogging)
      case 2: try decoder.decodeSingularBoolField(value: &self.clear)
      case 3: try decoder.decodeRepeatedInt64Field(value: &self.fetchStepID)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rpcLogging != false {
      try visitor.visitSingularBoolField(value: self.rpcLogging, fieldNumber: 1)
    }
    if self.clear != false {
      try visitor.visitSingularBoolField(value: self.clear, fieldNumber: 2)
    }
    if !self.fetchStepID.isEmpty {
      try visitor.visitPackedInt64Field(value: self.fetchStepID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_LabeledStepStats: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".LabeledStepStats"

  public var stepID: Int64 {
    get {return _storage._stepID}
    set {_uniqueStorage()._stepID = newValue}
  }

  public var stepStats: Tensorflow_StepStats {
    get {return _storage._stepStats ?? Tensorflow_StepStats()}
    set {_uniqueStorage()._stepStats = newValue}
  }
  /// Returns true if `stepStats` has been explicitly set.
  public var hasStepStats: Bool {return _storage._stepStats != nil}
  /// Clears the value of `stepStats`. Subsequent reads from it will return its default value.
  public mutating func clearStepStats() {_storage._stepStats = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularInt64Field(value: &_storage._stepID)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._stepStats)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._stepID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._stepID, fieldNumber: 1)
      }
      if let v = _storage._stepStats {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_LoggingResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".LoggingResponse"

  public var step: [Tensorflow_LabeledStepStats] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.step)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.step.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.step, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

public struct Tensorflow_TraceOpts: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".TraceOpts"

  /// Length of the trace to be taken, in seconds.
  public var duration: Double = 0

  /// If true, capture step profile locally in each worker. Currently
  /// unimplemented.
  public var useStepProfiler: Bool = false

  /// If true, capture kernel events from each worker.
  public var useKernelProfiler: Bool = false

  /// If true, capture extended profiling events from TensorFlow process.
  public var useExtendedProfiler: Bool = false

  /// If true, capture GPU profiling events locally on each
  /// machine. Currently unimplemented.
  public var useGpuProfiler: Bool = false

  /// If true, collect sampled profile events. Currently unimplemented.
  public var useSampleProfiler: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.duration)
      case 2: try decoder.decodeSingularBoolField(value: &self.useStepProfiler)
      case 3: try decoder.decodeSingularBoolField(value: &self.useKernelProfiler)
      case 4: try decoder.decodeSingularBoolField(value: &self.useExtendedProfiler)
      case 5: try decoder.decodeSingularBoolField(value: &self.useGpuProfiler)
      case 6: try decoder.decodeSingularBoolField(value: &self.useSampleProfiler)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.duration != 0 {
      try visitor.visitSingularDoubleField(value: self.duration, fieldNumber: 1)
    }
    if self.useStepProfiler != false {
      try visitor.visitSingularBoolField(value: self.useStepProfiler, fieldNumber: 2)
    }
    if self.useKernelProfiler != false {
      try visitor.visitSingularBoolField(value: self.useKernelProfiler, fieldNumber: 3)
    }
    if self.useExtendedProfiler != false {
      try visitor.visitSingularBoolField(value: self.useExtendedProfiler, fieldNumber: 4)
    }
    if self.useGpuProfiler != false {
      try visitor.visitSingularBoolField(value: self.useGpuProfiler, fieldNumber: 5)
    }
    if self.useSampleProfiler != false {
      try visitor.visitSingularBoolField(value: self.useSampleProfiler, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

/// Out-of-band request to configure distributed tracing.
public struct Tensorflow_TracingRequest: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".TracingRequest"

  public var options: Tensorflow_TraceOpts {
    get {return _storage._options ?? Tensorflow_TraceOpts()}
    set {_uniqueStorage()._options = newValue}
  }
  /// Returns true if `options` has been explicitly set.
  public var hasOptions: Bool {return _storage._options != nil}
  /// Clears the value of `options`. Subsequent reads from it will return its default value.
  public mutating func clearOptions() {_storage._options = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._options)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._options {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Tensorflow_TracingResponse: SwiftProtobuf.Message {
  public static let protoMessageName: String = _protobuf_package + ".TracingResponse"

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "tensorflow"

extension Tensorflow_GetStatusRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_GetStatusRequest) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_GetStatusResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "device_attributes"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_GetStatusResponse) -> Bool {
    if self.deviceAttributes != other.deviceAttributes {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CreateWorkerSessionRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "session_handle"),
    2: .standard(proto: "server_def"),
  ]

  fileprivate class _StorageClass {
    var _sessionHandle: String = String()
    var _serverDef: Tensorflow_ServerDef? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sessionHandle = source._sessionHandle
      _serverDef = source._serverDef
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CreateWorkerSessionRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._sessionHandle != other_storage._sessionHandle {return false}
        if _storage._serverDef != other_storage._serverDef {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CreateWorkerSessionResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CreateWorkerSessionResponse) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RegisterGraphRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "session_handle"),
    2: .standard(proto: "graph_def"),
    3: .standard(proto: "has_control_flow"),
    4: .standard(proto: "graph_options"),
    5: .standard(proto: "debug_options"),
  ]

  fileprivate class _StorageClass {
    var _sessionHandle: String = String()
    var _graphDef: Tensorflow_GraphDef? = nil
    var _hasControlFlow_p: Bool = false
    var _graphOptions: Tensorflow_GraphOptions? = nil
    var _debugOptions: Tensorflow_DebugOptions? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sessionHandle = source._sessionHandle
      _graphDef = source._graphDef
      _hasControlFlow_p = source._hasControlFlow_p
      _graphOptions = source._graphOptions
      _debugOptions = source._debugOptions
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RegisterGraphRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._sessionHandle != other_storage._sessionHandle {return false}
        if _storage._graphDef != other_storage._graphDef {return false}
        if _storage._hasControlFlow_p != other_storage._hasControlFlow_p {return false}
        if _storage._graphOptions != other_storage._graphOptions {return false}
        if _storage._debugOptions != other_storage._debugOptions {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RegisterGraphResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "graph_handle"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RegisterGraphResponse) -> Bool {
    if self.graphHandle != other.graphHandle {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_DeregisterGraphRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .standard(proto: "session_handle"),
    1: .standard(proto: "graph_handle"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_DeregisterGraphRequest) -> Bool {
    if self.sessionHandle != other.sessionHandle {return false}
    if self.graphHandle != other.graphHandle {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_DeregisterGraphResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_DeregisterGraphResponse) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CleanupAllRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "container"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CleanupAllRequest) -> Bool {
    if self.container != other.container {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CleanupAllResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CleanupAllResponse) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_ExecutorOpts: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "record_costs"),
    3: .standard(proto: "record_timeline"),
    4: .standard(proto: "record_partition_graphs"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_ExecutorOpts) -> Bool {
    if self.recordCosts != other.recordCosts {return false}
    if self.recordTimeline != other.recordTimeline {return false}
    if self.recordPartitionGraphs != other.recordPartitionGraphs {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RunGraphRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    8: .standard(proto: "session_handle"),
    1: .standard(proto: "graph_handle"),
    2: .standard(proto: "step_id"),
    5: .standard(proto: "exec_opts"),
    3: .same(proto: "send"),
    4: .standard(proto: "recv_key"),
    6: .standard(proto: "is_partial"),
    7: .standard(proto: "is_last_partial_run"),
  ]

  fileprivate class _StorageClass {
    var _sessionHandle: String = String()
    var _graphHandle: String = String()
    var _stepID: Int64 = 0
    var _execOpts: Tensorflow_ExecutorOpts? = nil
    var _send: [Tensorflow_NamedTensorProto] = []
    var _recvKey: [String] = []
    var _isPartial: Bool = false
    var _isLastPartialRun: Bool = false

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _sessionHandle = source._sessionHandle
      _graphHandle = source._graphHandle
      _stepID = source._stepID
      _execOpts = source._execOpts
      _send = source._send
      _recvKey = source._recvKey
      _isPartial = source._isPartial
      _isLastPartialRun = source._isLastPartialRun
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RunGraphRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._sessionHandle != other_storage._sessionHandle {return false}
        if _storage._graphHandle != other_storage._graphHandle {return false}
        if _storage._stepID != other_storage._stepID {return false}
        if _storage._execOpts != other_storage._execOpts {return false}
        if _storage._send != other_storage._send {return false}
        if _storage._recvKey != other_storage._recvKey {return false}
        if _storage._isPartial != other_storage._isPartial {return false}
        if _storage._isLastPartialRun != other_storage._isLastPartialRun {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RunGraphResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "recv"),
    2: .standard(proto: "step_stats"),
    3: .standard(proto: "cost_graph"),
    4: .standard(proto: "partition_graph"),
  ]

  fileprivate class _StorageClass {
    var _recv: [Tensorflow_NamedTensorProto] = []
    var _stepStats: Tensorflow_StepStats? = nil
    var _costGraph: Tensorflow_CostGraphDef? = nil
    var _partitionGraph: [Tensorflow_GraphDef] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _recv = source._recv
      _stepStats = source._stepStats
      _costGraph = source._costGraph
      _partitionGraph = source._partitionGraph
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RunGraphResponse) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._recv != other_storage._recv {return false}
        if _storage._stepStats != other_storage._stepStats {return false}
        if _storage._costGraph != other_storage._costGraph {return false}
        if _storage._partitionGraph != other_storage._partitionGraph {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CleanupGraphRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "step_id"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CleanupGraphRequest) -> Bool {
    if self.stepID != other.stepID {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_CleanupGraphResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_CleanupGraphResponse) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RecvTensorRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "step_id"),
    2: .standard(proto: "rendezvous_key"),
    3: .standard(proto: "dma_ok"),
    4: .standard(proto: "client_locality"),
    5: .standard(proto: "server_locality"),
    6: .standard(proto: "transport_options"),
  ]

  fileprivate class _StorageClass {
    var _stepID: Int64 = 0
    var _rendezvousKey: String = String()
    var _dmaOk: Bool = false
    var _clientLocality: Tensorflow_DeviceLocality? = nil
    var _serverLocality: Tensorflow_DeviceLocality? = nil
    var _transportOptions: SwiftProtobuf.Google_Protobuf_Any? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _stepID = source._stepID
      _rendezvousKey = source._rendezvousKey
      _dmaOk = source._dmaOk
      _clientLocality = source._clientLocality
      _serverLocality = source._serverLocality
      _transportOptions = source._transportOptions
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RecvTensorRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._stepID != other_storage._stepID {return false}
        if _storage._rendezvousKey != other_storage._rendezvousKey {return false}
        if _storage._dmaOk != other_storage._dmaOk {return false}
        if _storage._clientLocality != other_storage._clientLocality {return false}
        if _storage._serverLocality != other_storage._serverLocality {return false}
        if _storage._transportOptions != other_storage._transportOptions {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_RecvTensorResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "tensor"),
    2: .standard(proto: "is_dead"),
    3: .standard(proto: "send_start_micros"),
    4: .standard(proto: "transport_options"),
  ]

  fileprivate class _StorageClass {
    var _tensor: Tensorflow_TensorProto? = nil
    var _isDead: Bool = false
    var _sendStartMicros: Int64 = 0
    var _transportOptions: SwiftProtobuf.Google_Protobuf_Any? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _tensor = source._tensor
      _isDead = source._isDead
      _sendStartMicros = source._sendStartMicros
      _transportOptions = source._transportOptions
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_RecvTensorResponse) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._tensor != other_storage._tensor {return false}
        if _storage._isDead != other_storage._isDead {return false}
        if _storage._sendStartMicros != other_storage._sendStartMicros {return false}
        if _storage._transportOptions != other_storage._transportOptions {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_LoggingRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rpc_logging"),
    2: .same(proto: "clear"),
    3: .standard(proto: "fetch_step_id"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_LoggingRequest) -> Bool {
    if self.rpcLogging != other.rpcLogging {return false}
    if self.clear != other.clear {return false}
    if self.fetchStepID != other.fetchStepID {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_LabeledStepStats: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "step_id"),
    2: .standard(proto: "step_stats"),
  ]

  fileprivate class _StorageClass {
    var _stepID: Int64 = 0
    var _stepStats: Tensorflow_StepStats? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _stepID = source._stepID
      _stepStats = source._stepStats
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_LabeledStepStats) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._stepID != other_storage._stepID {return false}
        if _storage._stepStats != other_storage._stepStats {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_LoggingResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "step"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_LoggingResponse) -> Bool {
    if self.step != other.step {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_TraceOpts: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "duration"),
    2: .standard(proto: "use_step_profiler"),
    3: .standard(proto: "use_kernel_profiler"),
    4: .standard(proto: "use_extended_profiler"),
    5: .standard(proto: "use_gpu_profiler"),
    6: .standard(proto: "use_sample_profiler"),
  ]

  public func _protobuf_generated_isEqualTo(other: Tensorflow_TraceOpts) -> Bool {
    if self.duration != other.duration {return false}
    if self.useStepProfiler != other.useStepProfiler {return false}
    if self.useKernelProfiler != other.useKernelProfiler {return false}
    if self.useExtendedProfiler != other.useExtendedProfiler {return false}
    if self.useGpuProfiler != other.useGpuProfiler {return false}
    if self.useSampleProfiler != other.useSampleProfiler {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_TracingRequest: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "options"),
  ]

  fileprivate class _StorageClass {
    var _options: Tensorflow_TraceOpts? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _options = source._options
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public func _protobuf_generated_isEqualTo(other: Tensorflow_TracingRequest) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._options != other_storage._options {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension Tensorflow_TracingResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public func _protobuf_generated_isEqualTo(other: Tensorflow_TracingResponse) -> Bool {
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
